const { chromium } = require('playwright');
const assert = require('assert');
(async()=>{const b=await chromium.launch({headless:true});const p=await b.newPage({viewport:{width:1440,height:1000}});await p.goto('http://127.0.0.1:8765',{waitUntil:'networkidle'});
const result=await p.evaluate(()=>{const ids=(D._channels||[]).filter(x=>x.id!=='MT').map(x=>x.id), ranges=[[1,8],[1,3],[4,8]], failures=[];
function close(a,b){return Math.abs(a-b)<0.011} function test(tag){const c=C(),a=skuAuthoritative(c),rows=Object.keys(c.monthly_by_sku||{}).filter(n=>activeSku?n===activeSku:(activeCat?(c.monthly_by_sku[n]||{}).cat===activeCat:true)),ra=rows.reduce((s,n)=>s+rangeSum(c.monthly_by_sku[n].actual,selFrom,selTo),0),rl=rows.reduce((s,n)=>s+rangeSum(c.monthly_by_sku[n].ly,selFrom,selTo),0),foot=document.querySelector('#skuTable tfoot');if(!foot||!close(a.actual,rangeSum(currentFocus(c)?currentFocus(c).series.actual:actSeries(c),selFrom,selTo))||a.ly==null||!/100\.0%/.test(foot.textContent))failures.push({tag,a,ra,rl,footer:foot&&foot.textContent});}
for(const id of ids){selChans=[id];cur=id;activeCat=null;activeSku=null;for(const r of ranges){selFrom=r[0];selTo=r[1];renderAll();test(id+':'+r);}}
selChans=['MAKRO'];cur='MAKRO';selFrom=1;selTo=8;activeCat=null;activeSku=null;renderAll();const makro={auth:skuAuthoritative(C()),footer:[...document.querySelectorAll('#skuTable tfoot td')].map(x=>x.textContent.trim()),rows:document.querySelectorAll('#skuTable tbody tr').length};
const cat=Object.keys(C().monthly_by_cat)[0];activeCat=cat;renderAll();test('category:'+cat);const sku=Object.keys(C().monthly_by_sku).find(n=>C().monthly_by_sku[n].cat===cat);activeSku=sku;renderAll();test('sku:'+sku);
selChans=ids.slice();cur=ids[0];activeCat=null;activeSku=null;renderAll();test('all-channel');return {failures,makro};});assert.deepStrictEqual(result.failures,[]);assert(Math.abs(result.makro.auth.actual-54.19)<.011);assert(Math.abs(result.makro.auth.ly-88.81)<.011);console.log(JSON.stringify(result,null,2));await b.close();})().catch(e=>{console.error(e);process.exit(1)});
